
local thicknesses = {
  "factorio-like-belt-indicator",
  "factorio-like-pipe-indicator",
  "double-thick-line",
  "double-thin-line",
  "extra-thick-line",
  "thick-line",
  "thin-line"
}

local colors = {
  "white",
  "red",
  "blue",
  "green",
  "yellow",
  "magenta",
  "cyan"
}

data:extend({
  {
    type = "bool-setting",
    setting_type = "runtime-global",
    name = "underground-indicators-disable-belt-animation",
    default_value = false,
    order = "underground-indicators-aa",
  },
  {
    type = "bool-setting",
    setting_type = "runtime-global",
    name = "underground-indicators-disable-pipe-animation",
    default_value = false,
    order = "underground-indicators-ab",
  },
  {
    type = "string-setting",
    name = "underground-indicators-belt-thickness",
    setting_type = "runtime-global",
    default_value = "factorio-like-belt-indicator",
    allow_blank = false,
    allowed_values = thicknesses,
    order = "underground-indicators-ba",
  },
  {
    type = "string-setting",
    name = "underground-indicators-pipe-thickness",
    setting_type = "runtime-global",
    default_value = "factorio-like-pipe-indicator",
    allow_blank = false,
    allowed_values = thicknesses,
    order = "underground-indicators-bb",
  },
  {
    type = "int-setting",
    name = "underground-indicators-range",
    setting_type = "runtime-global",
    default_value = 40,
    maximum_value = 250,
    minimum_value = 1,
    order = "underground-indicators-c",
  },
  {
    type = "string-setting",
    name = "underground-indicators-color-normal",
    setting_type = "runtime-global",
    default_value = "white",
    allow_blank = false,
    allowed_values = colors,
    order = "underground-indicators-da",
  },
  {
    type = "string-setting",
    name = "underground-indicators-color-blocked",
    setting_type = "runtime-global",
    default_value = "red",
    allow_blank = false,
    allowed_values = colors,
    order = "underground-indicators-db",
  },
  {
    type = "string-setting",
    name = "underground-indicators-color-replaceable",
    setting_type = "runtime-global",
    default_value = "yellow",
    allow_blank = false,
    allowed_values = colors,
    order = "underground-indicators-dc",
  },
  {
    type = "bool-setting",
    name = "underground-indicators-placement-indicator",
    setting_type = "startup",
    default_value = true,
    order = "underground-indicators-ea",
  },
  {
    type = "string-setting",
    name = "underground-indicators-placement-belt",
    setting_type = "startup",
    default_value = "factorio-like-belt-indicator",
    allow_blank = false,
    allowed_values = thicknesses,
    order = "underground-indicators-eb",
  },
  {
    type = "string-setting",
    name = "underground-indicators-placement-pipe",
    setting_type = "startup",
    default_value = "factorio-like-pipe-indicator",
    allow_blank = false,
    allowed_values = thicknesses,
    order = "underground-indicators-ec",
  },
  {
    type = "string-setting",
    name = "underground-indicators-placement-color",
    setting_type = "startup",
    default_value = "white",
    allow_blank = false,
    allowed_values = colors,
    order = "underground-indicators-ed",
  }
})